### PR TITLE
Feat: Authentication Components added

### PR DESCRIPTION
**Pull request by bmendhe23**
##Description
Feat:
1. Added authentication component to the store website.

##Screenshots
ss1
ss2

##Platforms tested
[✔️] Desktop
[❌] Tablet
[❌] Mobile

### CODE REVIEW

**Review by sakshi006 — COMMENTED** [review]
Screenshot (545)
You can adjust the height of the button to align with the height of search bar.

Rest, good to merge!

**Comment by TusharJade** [comment]
Looks good to me👍

**Review by TusharJade — COMMENTED** [review]
Looks good to me👍

**Comment by ashifkhn** [comment]
Good to go.

**Comment by bmendhe23** [comment]
> Screenshot (545) You can adjust the height of the button to align with the height of search bar.
> 
> Rest, good to merge!

done @sakshi006

**Comment by bmendhe23** [comment]
thank you @sakshi006 @TusharJade @ashifkhn

**Pull request merged**
